In [110]:
import scipy.io as sio
import numpy as np
import pandas as pd
import matplotlib
from numpy import linalg
from numpy.linalg import inv

In [111]:
content = sio.loadmat('dataset2.mat')
X_train = np.array(content['X_trn'])
Y_train = np.array(content['Y_trn'])
X_test = content['X_tst']
Y_test = content['Y_tst']

In [112]:
N = X_train.shape[0]
K = [2,5,N]
penaltyLambdaList = [0.1, 0.01, 0.001, 0.0001, 0.00001, 0.000001, 0.0000001, 0.00000001, 0.000000001]

In [113]:
n = 2
k=5

In [114]:
X_c = []

initial_theta = np.random.rand(n+1,1)
for row in range(0,X_train.shape[0]):
    new_row = []
    x = X_train[row][0]
    for i in range(0, n+1):
        new_row.append(x**i)
    X_c.append(new_row)
    
X_capTrain2 = np.array(X_c)


holdOut = {}
thetaLambda = {}
for l in range(0, len(penaltyLambdaList)):
    penaltyLambda = penaltyLambdaList[l]
    Xchunks = np.array(np.split(X_capTrain2, k))
    Ychunks = np.array(np.split(Y_train, k))
    thetaMin = {}
    holdOutErrors = 0
    for i in range(0,len(Xchunks)):
        Xtest = Xchunks[i]
        Ytest = Ychunks[i]
        Xtrain = np.array(np.delete(Xchunks, i, 0))
        Xtrain = Xtrain.reshape((k-1*Xtrain.shape[1], Xtrain.shape[2]))
        Ytrain = np.array(np.delete(Ychunks, i, 0))
        Ytrain = Ytrain.reshape((k-1*Ytrain.shape[1], Ytrain.shape[2]))
        lambdaEye = np.multiply(penaltyLambda, np.eye(n+1,n+1))
        learningRate = 0.000000005
        epsilon = 0.00000001
        jThetaHalf1 = Xtrain.transpose().dot(np.subtract(Xtrain.dot(initial_theta), Ytrain))
        jThetaHalf2 = np.multiply(penaltyLambda, initial_theta)
        jTheta = np.add(jThetaHalf1, jThetaHalf2)
        for i in range(1000):
            nextVal = np.subtract(initial_theta, learningRate*jTheta)
            jThetaHalf1 = Xtrain.transpose().dot(np.subtract(Xtrain.dot(initial_theta), Ytrain))
            jThetaHalf2 = np.multiply(penaltyLambda, initial_theta)
            jTheta = np.add(jThetaHalf1, jThetaHalf2)
            if(linalg.norm(np.subtract(nextVal, initial_theta))<=epsilon):
                print("done")
                initial_val=nextVal
                break
            initial_theta=nextVal
        thetaMin[i] = initial_theta
        holdOutError = linalg.norm(np.subtract(Ytest, np.matmul(Xtest,initial_theta)))
        holdOutErrors += holdOutError
        #print(holdOutError)
    holdOutErrorLambda = holdOutErrors/k
    holdOut[penaltyLambda] = holdOutErrorLambda
    thetaLambda[penaltyLambda] = thetaMin
print(holdOut)

{0.1: 279.2863869845016, 0.01: 273.84101686396446, 0.001: 269.0175760810064, 0.0001: 263.96993422595654, 1e-05: 258.9936242402451, 1e-06: 254.18261230447456, 1e-07: 249.55634824776016, 1e-08: 245.11503129136116, 1e-09: 240.85425475630683}


In [115]:
lamda, error = min(holdOut.items(), key=lambda x: x[1]) 

In [116]:
lamda

1e-09

In [117]:
print("Theta")
initial_theta

Theta


array([[ 1.09561749],
       [ 4.18630248],
       [-0.22849998]])

In [118]:
n = 5
k = 5

In [119]:
X_c = []

initial_theta = np.random.rand(n+1,1)
for row in range(0,X_train.shape[0]):
    new_row = []
    x = X_train[row][0]
    for i in range(0, n+1):
        new_row.append(x**i)
    X_c.append(new_row)
    
X_capTrain2 = np.array(X_c)

holdOut = {}
thetaLambda = {}
for l in range(0, len(penaltyLambdaList)):
    penaltyLambda = penaltyLambdaList[l]
    Xchunks = np.array(np.split(X_capTrain2, k))
    Ychunks = np.array(np.split(Y_train, k))
    thetaMin = {}
    holdOutErrors = 0
    for i in range(0,len(Xchunks)):
        Xtest = Xchunks[i]
        Ytest = Ychunks[i]
        Xtrain = np.array(np.delete(Xchunks, i, 0))
        Xtrain = Xtrain.reshape((k-1*Xtrain.shape[1], Xtrain.shape[2]))
        Ytrain = np.array(np.delete(Ychunks, i, 0))
        Ytrain = Ytrain.reshape((k-1*Ytrain.shape[1], Ytrain.shape[2]))
        lambdaEye = np.multiply(penaltyLambda, np.eye(n+1,n+1))
        learningRate = 0.00000000005
        epsilon = 0.00000001
        jThetaHalf1 = Xtrain.transpose().dot(np.subtract(Xtrain.dot(initial_theta), Ytrain))
        jThetaHalf2 = np.multiply(penaltyLambda, initial_theta)
        jTheta = np.add(jThetaHalf1, jThetaHalf2)
        for i in range(1000):
            nextVal = np.subtract(initial_theta, learningRate*jTheta)
            jThetaHalf1 = Xtrain.transpose().dot(np.subtract(Xtrain.dot(initial_theta), Ytrain))
            jThetaHalf2 = np.multiply(penaltyLambda, initial_theta)
            jTheta = np.add(jThetaHalf1, jThetaHalf2)
            if(linalg.norm(np.subtract(nextVal, initial_theta))<=epsilon):
                print("done")
                initial_val=nextVal
                break
            initial_theta=nextVal
        thetaMin[i] = initial_theta
        holdOutError = linalg.norm(np.subtract(Ytest, np.matmul(Xtest,initial_theta)))
        holdOutErrors += holdOutError
        #print(holdOutError)
    holdOutErrorLambda = holdOutErrors/k
    holdOut[penaltyLambda] = holdOutErrorLambda
    thetaLambda[penaltyLambda] = thetaMin
print(holdOut)

{0.1: 338.6225794573378, 0.01: 120.11780866786894, 0.001: 116.70419479906582, 0.0001: 113.40180969586709, 1e-05: 110.23345200567712, 1e-06: 107.19484106898469, 1e-07: 104.28174874748781, 1e-08: 101.49006810909637, 1e-09: 98.81580773289853}


In [120]:
lamda, error = min(holdOut.items(), key=lambda x: x[1]) 

In [121]:
lamda

1e-09

In [122]:
print("Theta")
initial_theta

Theta


array([[ 0.63244078],
       [ 0.32747986],
       [ 0.72080729],
       [ 0.74303964],
       [ 0.01927515],
       [-0.00443613]])

In [123]:
n = 5
k = N

In [124]:
X_c = []

initial_theta = np.random.rand(n+1,1)
for row in range(0,X_train.shape[0]):
    new_row = []
    x = X_train[row][0]
    for i in range(0, n+1):
        new_row.append(x**i)
    X_c.append(new_row)
    
X_capTrain2 = np.array(X_c)

holdOut = {}
thetaLambda = {}
for l in range(0, len(penaltyLambdaList)):
    penaltyLambda = penaltyLambdaList[l]
    Xchunks = np.array(np.split(X_capTrain2, k))
    Ychunks = np.array(np.split(Y_train, k))
    thetaMin = {}
    holdOutErrors = 0
    for i in range(0,len(Xchunks)):
        Xtest = Xchunks[i]
        Ytest = Ychunks[i]
        Xtrain = np.array(np.delete(Xchunks, i, 0))
        Xtrain = Xtrain.reshape((k-1*Xtrain.shape[1], Xtrain.shape[2]))
        Ytrain = np.array(np.delete(Ychunks, i, 0))
        Ytrain = Ytrain.reshape((k-1*Ytrain.shape[1], Ytrain.shape[2]))
        lambdaEye = np.multiply(penaltyLambda, np.eye(n+1,n+1))
        learningRate = 0.000000000005
        epsilon = 0.00000001
        jThetaHalf1 = Xtrain.transpose().dot(np.subtract(Xtrain.dot(initial_theta), Ytrain))
        jThetaHalf2 = np.multiply(penaltyLambda, initial_theta)
        jTheta = np.add(jThetaHalf1, jThetaHalf2)
        for i in range(3000):
            nextVal = np.subtract(initial_theta, learningRate*jTheta)
            jThetaHalf1 = Xtrain.transpose().dot(np.subtract(Xtrain.dot(initial_theta), Ytrain))
            jThetaHalf2 = np.multiply(penaltyLambda, initial_theta)
            jTheta = np.add(jThetaHalf1, jThetaHalf2)
            if(linalg.norm(np.subtract(nextVal, initial_theta))<=0.0000000001):
                print("done")
                initial_val=nextVal
                break
            initial_theta=nextVal
        thetaMin[i] = initial_theta
        holdOutError = linalg.norm(np.subtract(Ytest, np.matmul(Xtest,initial_theta)))
        holdOutErrors += holdOutError
        #print(holdOutError)
    holdOutErrorLambda = holdOutErrors/k
    holdOut[penaltyLambda] = holdOutErrorLambda
    thetaLambda[penaltyLambda] = thetaMin
print(holdOut)

{0.1: 16.101308066365892, 0.01: 9.976651252468592, 0.001: 9.95673881524269, 0.0001: 9.944819346649362, 1e-05: 9.932293581589683, 1e-06: 9.922078603160992, 1e-07: 9.916297911359399, 1e-08: 9.908443346475256, 1e-09: 9.899001272468494}


In [125]:
lamda, error = min(holdOut.items(), key=lambda x: x[1]) 

In [126]:
lamda

1e-09

In [127]:
print("Theta")
initial_theta

Theta


array([[0.99205809],
       [0.08397893],
       [0.54288499],
       [0.28556038],
       [0.04189896],
       [0.00679087]])