In [1]:
import scipy.io as sio
import numpy as np
import sys
import random 
from sklearn.metrics import accuracy_score

In [2]:
content = sio.loadmat('dataset1.mat')

In [3]:
X_train = np.array(content['X_trn'])
Y_train = np.array(content['Y_trn'])
X_test = content['X_tst']
Y_test = content['Y_tst']

In [4]:
C = 2
tol = 10**-4
max_passes = 150
m = X_train.shape[0]
alpha = np.zeros(m)
b = 0
passes = 0
E = [0] * m
alpha_old = alpha

In [5]:
def innerProduct(a, b):
    return a.dot(b)

In [6]:
def f(X):
    return sum([alpha[i]*Y_train[i]*innerProduct(X_train[i,:], X) for i in range(m)]) + b

In [7]:
for i in range(0, len(Y_train)):
    if Y_train[i] == 0:
        Y_train[i] = -1

In [8]:
while(passes < max_passes):
    num_changed_alphas = 0
    for i in range(0, m):
        E[i] = f(X_train[i, :]) - Y_train[i]
        if ((Y_train[i] * E[i] < -tol and alpha[i] < C) or (Y_train[i]*E[i] > tol and alpha[i] > 0)):
            numbers = list(range(0,i)) + list(range(i+1,m))
            j = random.choice(numbers)
            E[j] = f(X_train[j, :]) - Y_train[j]
            alpha_old[i] = alpha[i]
            alpha_old[j] = alpha[j]
            if Y_train[i] != Y_train[j]:
                L = max(0, alpha[j] - alpha[i])
                H = min(C, C + alpha[j] - alpha[i])
            if Y_train[i] == Y_train[j]:
                L = max(0, alpha[i] + alpha[j] - C)
                H = min (C, alpha[i] + alpha[j])
            if L == H:
                continue
            eta = 2 * innerProduct(X_train[i, :], X_train[j, :]) - innerProduct(X_train[i, :], X_train[i, :]) - innerProduct(X_train[j, :], X_train[j, :])
            if eta >= 0:
                continue
            alpha[j] = alpha[j] - ((Y_train[j] * (E[i] - E[j])) / eta)
            if alpha[j] > H:
                alpha[j] = H
            elif alpha[j] < L:
                alpha[j] = L
            elif alpha[j] >= L and alpha[j] <= H:
                alpha[j] = alpha[j]
            if (abs(alpha[j] - alpha_old[j]) < 10**-5):
                continue
            alpha[i] = alpha[i] + Y_train[i] * Y_train[j] * (alpha_old[j] - alpha[j])
            b1 = b - E[i] - Y_train[i] * (alpha[i] - alpha_old[i]) * innerProduct(X_train[i, :], X_train[i, :]) - Y_train[j] * (alpha[j] - alpha_old[j]) * innerProduct(X_train[i, :], X_train[j, :])
            b2 = b - E[j] - Y_train[i] * (alpha[i] - alpha_old[i]) * innerProduct(X_train[i, :], X_train[j, :]) - Y_train[j] * (alpha[j] - alpha_old[j]) * innerProduct(X_train[j, :], X_train[j, :])
            if alpha[i] > 0 and alpha[i] < C:
                b = b1
            elif alpha[j] > 0 and alpha[j] < C:
                b = b2
            else:
                b = (b1 + b2) / 2
            num_changed_alphas += 1
    if (num_changed_alphas == 0):
        passes += 1
    else:
        passes = 0

In [9]:
predictions = []
for i in range(X_test.shape[0]):
    predictions.append(f(X_test[i,:]) > 0)
predictions

[array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False])]

In [10]:
Y_test

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=uint8)

### Classification Error on test data

In [11]:
normalized_predictions = []


for prediction in predictions:
    if prediction[0]:
        normalized_predictions.append(0)
    else:
        normalized_predictions.append(1)

In [12]:
normalized_predictions

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]

In [13]:
my_accuracy = accuracy_score(Y_test, normalized_predictions) * 100

my_accuracy

100.0

From the accuracy score, we can observe that there is no error. 

## Classification Error on training data

In [14]:
predictions_train = []
for i in range(X_train.shape[0]):
    predictions_train.append(f(X_train[i,:]) > 0)
predictions_train

[array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([ True]

In [15]:
normalized_predictions_train = []


for prediction in predictions_train:
    if prediction[0]:
        normalized_predictions_train.append(255)
    else:
        normalized_predictions_train.append(1)

In [16]:
my_accuracy = accuracy_score(Y_train, normalized_predictions_train) * 100

my_accuracy

94.11764705882352

From the accuracy score calculated above, we can observe that there is very less classification error

The C parameter tells us how much we want to avoid misclassifying training data. For larger values of C, the SVM will choose a smaller-margin hyperplane if that hyperplane does a better job of getting all the training points classified correctly. Very small values of C will create a hyperplane with large margin, even if there are more points misclassified. 