In [1]:
import scipy.io as sio
import numpy as np
from numpy import linalg
from numpy.linalg import inv

In [2]:
content = sio.loadmat('dataset1.mat')

In [3]:
X_train = np.array(content['X_trn'])
Y_train = np.array(content['Y_trn'])
X_test = content['X_tst']
Y_test = content['Y_tst']

In [4]:
learningRate = 0.00000011 #for n=3 0.00000011
#learningRate = 0.00001 #for n = 2 
n=3

In [5]:
X_c = []

initial_theta = np.random.rand(n+1,1)
for row in range(0,X_train.shape[0]):
    new_row = []
    x = X_train[row][0]
    for i in range(0, n+1):
        new_row.append(x**i)
    X_c.append(new_row)
    
X_capTrain = np.array(X_c)
jTheta = np.multiply(2,X_capTrain.transpose()).dot(np.subtract(X_capTrain.dot(initial_theta), Y_train))

epsilon = 0.000000001
for i in range(10000):
    nextVal = np.subtract(initial_theta, learningRate*jTheta)
    jTheta = 2*X_capTrain.transpose().dot(np.subtract(X_capTrain.dot(nextVal), Y_train))
    if(linalg.norm(np.subtract(nextVal, initial_theta))<=epsilon):
        print("converged")
        initial_theta = nextVal
        break
    initial_theta=nextVal
    #print(initial_theta.shape)
    costFunction = np.linalg.norm(np.subtract(X_capTrain.dot(initial_theta), Y_train), 2)**2
    #print(nextVal)
    #print(costFunction)
    
print(initial_theta)
XTheta = X_capTrain.dot(initial_theta)
t = np.subtract(XTheta, Y_train)
errorTrain = np.linalg.norm(t,2)**2/Y_train.shape[0]
print(errorTrain)

[[1.32832778]
 [0.91395256]
 [2.37548722]
 [0.41082418]]
36.75147585277456


In [6]:
X_train=X_test
Y_train=Y_test

X_c = []

initial_theta = np.random.rand(n+1,1)
for row in range(0,X_train.shape[0]):
    new_row = []
    x = X_train[row][0]
    for i in range(0, n+1):
        new_row.append(x**i)
    X_c.append(new_row)
    
X_capTrain = np.array(X_c)
jTheta = np.multiply(2,X_capTrain.transpose()).dot(np.subtract(X_capTrain.dot(initial_theta), Y_train))
epsilon = 0.000000001
for i in range(10000):
    nextVal = np.subtract(initial_theta, learningRate*jTheta)
    jTheta = 2*X_capTrain.transpose().dot(np.subtract(X_capTrain.dot(nextVal), Y_train))
    if(linalg.norm(np.subtract(nextVal, initial_theta))<=epsilon):
        print("converged")
        initial_theta = nextVal
        break
    initial_theta=nextVal
    #print(initial_theta.shape)
    costFunction = np.linalg.norm(np.subtract(X_capTrain.dot(initial_theta), Y_train), 2)**2
    #print(nextVal)
    #print(costFunction)
    
print(initial_theta)
XTheta = X_capTrain.dot(initial_theta)
t = np.subtract(XTheta, Y_train)
errorTrain = np.linalg.norm(t,2)**2/Y_train.shape[0]
print(errorTrain)

[[ 1.01419935]
 [-0.32837596]
 [ 1.83486591]
 [ 0.52944642]]
72.57673222222411


In [7]:
learningRate = 0.00001 
n=2

In [8]:
X_train = np.array(content['X_trn'])
Y_train = np.array(content['Y_trn'])
X_test = content['X_tst']
Y_test = content['Y_tst']

In [9]:
X_c = []

initial_theta = np.random.rand(n+1,1)
for row in range(0,X_train.shape[0]):
    new_row = []
    x = X_train[row][0]
    for i in range(0, n+1):
        new_row.append(x**i)
    X_c.append(new_row)
    
X_capTrain = np.array(X_c)
jTheta = np.multiply(2,X_capTrain.transpose()).dot(np.subtract(X_capTrain.dot(initial_theta), Y_train))

epsilon = 0.000000001
for i in range(10000):
    nextVal = np.subtract(initial_theta, learningRate*jTheta)
    jTheta = 2*X_capTrain.transpose().dot(np.subtract(X_capTrain.dot(nextVal), Y_train))
    if(linalg.norm(np.subtract(nextVal, initial_theta))<=epsilon):
        print("converged")
        initial_theta = nextVal
        break
    initial_theta=nextVal
    #print(initial_theta.shape)
    costFunction = np.linalg.norm(np.subtract(X_capTrain.dot(initial_theta), Y_train), 2)**2
    #print(nextVal)
    #print(costFunction)
    
print(initial_theta)
XTheta = X_capTrain.dot(initial_theta)
t = np.subtract(XTheta, Y_train)
errorTrain = np.linalg.norm(t,2)**2/Y_train.shape[0]
print(errorTrain)

[[9.49175381]
 [4.79191925]
 [1.52909527]]
24.74191967133081


In [10]:
X_train=X_test
Y_train=Y_test

X_c = []

initial_theta = np.random.rand(n+1,1)
for row in range(0,X_train.shape[0]):
    new_row = []
    x = X_train[row][0]
    for i in range(0, n+1):
        new_row.append(x**i)
    X_c.append(new_row)
    
X_capTrain = np.array(X_c)
jTheta = np.multiply(2,X_capTrain.transpose()).dot(np.subtract(X_capTrain.dot(initial_theta), Y_train))
epsilon = 0.000000001
for i in range(10000):
    nextVal = np.subtract(initial_theta, learningRate*jTheta)
    jTheta = 2*X_capTrain.transpose().dot(np.subtract(X_capTrain.dot(nextVal), Y_train))
    if(linalg.norm(np.subtract(nextVal, initial_theta))<=epsilon):
        print("converged")
        initial_theta = nextVal
        break
    initial_theta=nextVal
    #print(initial_theta.shape)
    costFunction = np.linalg.norm(np.subtract(X_capTrain.dot(initial_theta), Y_train), 2)**2
    #print(nextVal)
    #print(costFunction)
    
print(initial_theta)
XTheta = X_capTrain.dot(initial_theta)
t = np.subtract(XTheta, Y_train)
errorTrain = np.linalg.norm(t,2)**2/Y_train.shape[0]
print(errorTrain)

[[31.00410141]
 [13.13123747]
 [-0.28773709]]
772.2515530798773
